# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-01 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conversations.Message', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bddc903c-bf9c-4d8e-ab3b-f9ae06c754eb')),
        ),
    ]
