# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-09 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_added_is_internal_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_public_note',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9f32bf63-3ac6-438e-9fc2-535a1781ec27')),
        ),
    ]
