# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-09 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_added_is_public_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3b3ebb74-7cb2-49b1-955e-dde984ebf6f8')),
        ),
    ]
