# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-09 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_added_metadata_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='metadata',
        ),
        migrations.AddField(
            model_name='thread',
            name='metadata',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2e962556-e09b-4a04-a987-39f5a86d67e1')),
        ),
    ]
