# Generated by Django 2.2.10 on 2020-02-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('cms_utils', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarkitUpPluginModel',
        ),
    ]
