# Generated by Django 2.2.17 on 2020-12-03 18:26

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssopyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('assopy_id', models.CharField(max_length=22, null=True, unique=True)),
                ('card_name', models.CharField(blank=True, help_text='The name used for orders and invoices', max_length=200, verbose_name='Card name')),
                ('vat_number', models.CharField(blank=True, help_text='Your VAT number if applicable', max_length=22, verbose_name='Vat Number')),
                ('cf_code', models.CharField(blank=True, help_text='Needed only for Italian customers', max_length=16, verbose_name='Fiscal Code')),
                ('address', models.CharField(blank=True, help_text='Insert the full address, including city and zip code. We will help you through google.', max_length=150, verbose_name='Address and City')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('iso', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='ISO alpha-2')),
                ('name', models.CharField(max_length=100)),
                ('vat_company', models.BooleanField(default=False, verbose_name='VAT for company')),
                ('vat_company_verify', models.CharField(choices=[('-', 'None'), ('v', 'VIES')], default='-', max_length=1)),
                ('vat_person', models.BooleanField(default=False, verbose_name='VAT for person')),
                ('iso3', models.CharField(max_length=3, null=True, verbose_name='ISO alpha-3')),
                ('numcode', models.PositiveSmallIntegerField(null=True, verbose_name='ISO numeric')),
                ('printable_name', models.CharField(max_length=128, verbose_name='Country name')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('start_validity', models.DateField(blank=True, null=True)),
                ('end_validity', models.DateField(blank=True, null=True)),
                ('max_usage', models.PositiveIntegerField(default=0, help_text='numero di volte che questo coupon può essere usato')),
                ('items_per_usage', models.PositiveIntegerField(default=0, help_text="numero di righe d'ordine su cui questo coupon ha effetto")),
                ('description', models.CharField(blank=True, max_length=100)),
                ('value', models.CharField(help_text='importo, eg: 10, 15%, 8.5', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True, unique=True)),
                ('assopy_id', models.CharField(blank=True, max_length=22, null=True, unique=True)),
                ('emit_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('issuer', models.TextField()),
                ('customer', models.TextField()),
                ('html', models.TextField()),
                ('local_currency', models.CharField(default='EUR', max_length=3)),
                ('vat_in_local_currency', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('exchange_rate', models.DecimalField(decimal_places=5, default=Decimal('1'), max_digits=10)),
                ('exchange_rate_date', models.DateField(default=datetime.date(2000, 1, 1))),
                ('note', models.TextField(blank=True, help_text="Testo libero da riportare in fattura; posto al termine delle righe d'ordine riporta di solito gli estremi di legge")),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.CharField(max_length=20, null=True)),
                ('assopy_id', models.CharField(blank=True, max_length=22, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('cc', 'Credit Card'), ('paypal', 'PayPal (deprecated)'), ('bank', 'Bank')], max_length=6)),
                ('payment_url', models.TextField(blank=True)),
                ('_complete', models.BooleanField(default=False)),
                ('billing_notes', models.TextField(blank=True, help_text='Notes that you want to put on the invoice. Additional email address, employee name, things required by your internal accounting department, etc.', verbose_name='Additional billing notes')),
                ('card_name', models.CharField(max_length=200, verbose_name='Card name')),
                ('vat_number', models.CharField(blank=True, max_length=22, verbose_name='Vat Number')),
                ('cf_code', models.CharField(blank=True, max_length=16, verbose_name='Fiscal Code')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Address')),
                ('stripe_charge_id', models.CharField(max_length=64, null=True, unique=True, verbose_name='Charge Stripe ID')),
                ('payment_date', models.DateTimeField(blank=True, help_text='Auto filled by the payments backend', null=True)),
                ('order_type', models.CharField(blank=True, choices=[('company', 'Company'), ('student', 'Student'), ('personal', 'Personal'), ('other', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('ctype', models.CharField(choices=[('v', 'New signup email verification'), ('j', 'UNKOWN - probably related to Janrain')], max_length=1)),
                ('payload', models.TextField(blank='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=125, null=True)),
                ('invoice_notice', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VatFare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
