# Generated by Django 2.2.17 on 2020-12-03 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assopy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatfare',
            name='fare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Fare'),
        ),
        migrations.AddField(
            model_name='vatfare',
            name='vat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assopy.Vat'),
        ),
        migrations.AddField(
            model_name='vat',
            name='fares',
            field=models.ManyToManyField(blank=True, null=True, through='assopy.VatFare', to='conference.Fare'),
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assopy.Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.Ticket'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assopy.Vat'),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assopy.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='assopy.AssopyUser'),
        ),
        migrations.AddField(
            model_name='invoicelog',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assopy.Invoice'),
        ),
        migrations.AddField(
            model_name='invoicelog',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assopy.Order'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='assopy.Order'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assopy.Vat'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='fares',
            field=models.ManyToManyField(blank=True, to='conference.Fare'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assopy.AssopyUser'),
        ),
        migrations.AddField(
            model_name='assopyuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assopy.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='assopyuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assopy_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vatfare',
            unique_together={('fare', 'vat')},
        ),
    ]
