
# Generated by Django 1.9.13 on 2018-10-15 12:28


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assopy', '0007_add_customer_to_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroauthinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserOAuthInfo',
        ),
    ]
