# Generated by Django 1.11.16 on 2018-10-27 10:51
from __future__ import unicode_literals
import sqlite3

from django.db import migrations


class Migration(migrations.Migration):
    # This was added because the pipelines in Github don't have a version of
    # SQLite>3.26 and this migration fails on versions before that.
    if sqlite3.sqlite_version_info[1] < 27:
        atomic = False

    dependencies = [
        ('assopy', '0008_remove_user_oauth_info_model'),
        ('p3', '0002_remove_unused_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AssopyUser',
        ),
    ]
