# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-17 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assopy', '0009_rename_assopy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
