# Generated by Django 1.11.20 on 2019-05-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("assopy", "0011_updated_vat_settings_for_swiss_vat")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("company", "Company"),
                    ("student", "Student"),
                    ("personal", "Personal"),
                ],
                max_length=20,
            ),
        )
    ]
