# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assopy', '0012_add_type_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='vat_company',
            field=models.BooleanField(default=False, verbose_name='VAT for company'),
        ),
        migrations.AlterField(
            model_name='country',
            name='vat_company_verify',
            field=models.CharField(choices=[('-', 'None'), ('v', 'VIES')], default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='country',
            name='vat_person',
            field=models.BooleanField(default=False, verbose_name='VAT for person'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='items_per_usage',
            field=models.PositiveIntegerField(default=0, help_text="numero di righe d'ordine su cui questo coupon ha effetto"),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_usage',
            field=models.PositiveIntegerField(default=0, help_text='numero di volte che questo coupon può essere usato'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.CharField(help_text='importo, eg: 10, 15%, 8.5', max_length=8),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='local_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='note',
            field=models.TextField(blank=True, help_text="Testo libero da riportare in fattura; posto al termine delle righe d'ordine riporta di solito gli estremi di legge"),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_notes',
            field=models.TextField(blank=True, help_text='Notes that you want to put on the invoice. Additional email address, employee name, things required by your internal accounting department, etc.', verbose_name='Additional billing notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(choices=[('cc', 'Credit Card'), ('paypal', 'PayPal'), ('bank', 'Bank')], max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('student', 'Student'), ('personal', 'Personal'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='Auto filled by the payments backend', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='refund',
            name='internal_note',
            field=models.TextField(blank=True, help_text='For internal use (not shown to the user)'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reject_reason',
            field=models.TextField(blank=True, help_text='Included in the email sent to the user'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='token',
            name='ctype',
            field=models.CharField(choices=[('v', 'New signup email verification'), ('j', 'UNKOWN - probably related to Janrain')], max_length=1),
        ),
        migrations.AlterField(
            model_name='token',
            name='payload',
            field=models.TextField(blank=''),
        ),
    ]
