# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-24 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assopy', '0013_mystery_migrations_maybe_2_to_3_bytes_to_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(choices=[('cc', 'Credit Card'), ('paypal', 'PayPal (deprecated)'), ('bank', 'Bank')], max_length=6),
        ),
    ]
