# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-11 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assopy', '0014_deprecate_paypal_20191124_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='credit_note',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='items',
        ),
        migrations.AlterUniqueTogether(
            name='refundorderitem',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='refundorderitem',
            name='orderitem',
        ),
        migrations.RemoveField(
            model_name='refundorderitem',
            name='refund',
        ),
        migrations.RemoveField(
            model_name='useridentity',
            name='user',
        ),
        migrations.DeleteModel(
            name='CreditNote',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.DeleteModel(
            name='RefundOrderItem',
        ),
        migrations.DeleteModel(
            name='UserIdentity',
        ),
    ]
