# Generated by Django 2.2.19 on 2021-05-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assopy', '0015_remove_refund_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vat',
            name='fares',
            field=models.ManyToManyField(blank=True, through='assopy.VatFare', to='conference.Fare'),
        ),
    ]
