# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-04 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assopy', '0015_remove_refund_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vat',
            name='fares',
            field=models.ManyToManyField(blank=True, through='assopy.VatFare', to='conference.Fare'),
        ),
    ]
