# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcomments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hcomment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='hcomment',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='hcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='hcomment',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='hcomment',
            name='tree_id',
        ),
    ]
