# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcomments', '0002_remove_mptt_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='threadsubscription',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='threadsubscription',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='threadsubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='ThreadSubscription',
        ),
    ]
