# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-09 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [("conference", "0007_remove_special_place")]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        default=uuid.uuid4, max_length=40, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("content", models.TextField()),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Draft"),
                            (10, "Published"),
                            (20, "Deleted"),
                        ]
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conference.Conference",
                    ),
                ),
            ],
            options={"ordering": ["-published_date"]},
        )
    ]
