# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-01 15:37
from __future__ import unicode_literals

import conference.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_remove_special_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeeprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to=conference.models._fs_upload_to('profile')),
        ),
        migrations.AlterField(
            model_name='attendeeprofile',
            name='visibility',
            field=models.CharField(choices=[('x', 'Private (disabled)'), ('m', 'Participants only'), ('p', 'Public')], default='x', max_length=1),
        ),
        migrations.AlterField(
            model_name='conferencetag',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='didyouknow',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
        migrations.AlterField(
            model_name='event',
            name='abstract',
            field=models.TextField(blank=True, help_text='description for a custom event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='custom',
            field=models.TextField(blank=True, help_text='title for a custom event (an event without a talk)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='duration of the event (in minutes). Override the talk duration if present'),
        ),
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.PositiveIntegerField(default=0, help_text='seats available. Override the track default if set'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, help_text='comma separated list of tags. Something like: special, break, keynote', max_length=200),
        ),
        migrations.AlterField(
            model_name='fare',
            name='conference',
            field=models.CharField(help_text='Conference code', max_length=20),
        ),
        migrations.AlterField(
            model_name='fare',
            name='payment_type',
            field=models.CharField(choices=[('p', 'Payment'), ('v', 'Voucher'), ('d', 'Deposit')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='fare',
            name='recipient_type',
            field=models.CharField(choices=[('c', 'Company'), ('s', 'Student'), ('p', 'Personal')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='fare',
            name='ticket_type',
            field=models.CharField(choices=[('conference', 'Conference ticket'), ('partner', 'Partner Program'), ('event', 'Event'), ('other', 'Other')], db_index=True, default='conference', max_length=10),
        ),
        migrations.AlterField(
            model_name='mediapartner',
            name='logo',
            field=models.ImageField(blank=True, help_text='Insert a raster image big enough to be scaled as needed', upload_to=conference.models._fs_upload_to('media-partner')),
        ),
        migrations.AlterField(
            model_name='mediapartner',
            name='partner',
            field=models.CharField(help_text='The media partner name', max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='image',
            field=models.ImageField(blank=True, upload_to=conference.models._fs_upload_to('quote', 'who')),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='conference',
            field=models.CharField(help_text='nome della conferenza', max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, help_text='Insert a raster image big enough to be scaled as needed', upload_to=conference.models._fs_upload_to('sponsor')),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor',
            field=models.CharField(help_text='Name of the sponsor', max_length=100),
        ),
        migrations.AlterField(
            model_name='talk',
            name='abstract_extra',
            field=models.TextField(blank=True, default='', help_text='<p>Please enter instructions for attendees.</p>', verbose_name='Talk abstract extra'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='abstract_short',
            field=models.TextField(default='', help_text='<p>Please enter a short description of the talk you are submitting.</p>', verbose_name='Talk abstract short'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='admin_type',
            field=models.CharField(blank=True, choices=[('o', 'Opening session'), ('c', 'Closing session'), ('l', 'Lightning talk'), ('k', 'Keynote'), ('r', 'Recruiting session'), ('m', 'EPS session'), ('p', 'Community session'), ('s', 'Open space'), ('e', 'Social event'), ('x', 'Reserved slot'), ('z', 'Sponsored session')], max_length=1),
        ),
        migrations.AlterField(
            model_name='talk',
            name='conference',
            field=models.CharField(help_text='name of the conference', max_length=20),
        ),
        migrations.AlterField(
            model_name='talk',
            name='domain',
            field=models.CharField(blank=True, choices=[('business_track', 'Business Track'), ('devops', 'DevOps'), ('django', 'Django Track'), ('education', 'Educational Track'), ('general', 'General Python'), ('hw_iot', 'Hardware/IoT Track'), ('pydata', 'PyData Track'), ('science', 'Science Track'), ('web', 'Web Track'), ('', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='talk',
            name='domain_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=12, verbose_name='Audience Domain Level'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='language',
            field=models.CharField(choices=[('en', 'English')], default='en', max_length=3, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=12, verbose_name='Audience Python level'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='prerequisites',
            field=models.CharField(blank=True, default='', help_text='What should attendees know already', max_length=150, verbose_name='prerequisites'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='slides',
            field=models.FileField(blank=True, upload_to=conference.models._fs_upload_to('slides')),
        ),
        migrations.AlterField(
            model_name='talk',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('canceled', 'Canceled'), ('waitlist', 'Waitlist')], max_length=8),
        ),
        migrations.AlterField(
            model_name='talk',
            name='sub_title',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Sub title'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='type',
            field=models.CharField(choices=[('t_30', 'Talk (30 mins)'), ('t_45', 'Talk (45 mins)'), ('t_60', 'Talk (60 mins)'), ('i_60', 'Interactive (60 mins)'), ('r_180', 'Training (180 mins)'), ('p_180', 'Poster session (180 mins)'), ('n_60', 'Panel (60 mins)'), ('n_90', 'Panel (90 mins)'), ('h_180', 'Help desk (180 mins)')], default='t_30', max_length=5),
        ),
        migrations.AlterField(
            model_name='talk',
            name='video_file',
            field=models.FileField(blank=True, upload_to=conference.models._fs_upload_to('videos')),
        ),
        migrations.AlterField(
            model_name='talk',
            name='video_type',
            field=models.CharField(blank=True, choices=[('viddler_oembed', 'oEmbed (Youtube, Vimeo, ...)'), ('download', 'Download')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('standard', 'standard'), ('staff', 'staff')], default='standard', max_length=8),
        ),
        migrations.AlterField(
            model_name='track',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordine'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.TextField(help_text='HTML supportato', verbose_name='titolo della track'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.CharField(max_length=20, verbose_name='nome track'),
        ),
    ]
