# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-06 15:37
from __future__ import unicode_literals

import conference.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_remove_special_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
