# Generated by Django 1.11.20 on 2019-04-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0009_add_field_created_by_and_modified_to_talk")
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-published_date"],
                "verbose_name_plural": "News",
            },
        ),
        migrations.AddField(
            model_name="attendeeprofile",
            name="gender",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="attendeeprofile",
            name="is_minor",
            field=models.BooleanField(default=False),
        ),
    ]
