# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 11:32
from __future__ import unicode_literals

import conference.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0012_add_vototalk_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayment',
            name='charge_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
