# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-10 11:52
from __future__ import unicode_literals

import conference.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0013_add_stripe_charge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=40, unique=True),
        ),
    ]
