# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-10 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0016_mystery_migrations_maybe_2_to_3_bytes_to_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendeelink',
            name='attendee1',
        ),
        migrations.RemoveField(
            model_name='attendeelink',
            name='attendee2',
        ),
        migrations.RemoveField(
            model_name='mediapartnerconference',
            name='partner',
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='presence',
            name='profile',
        ),
        migrations.DeleteModel(
            name='AttendeeLink',
        ),
        migrations.DeleteModel(
            name='MediaPartner',
        ),
        migrations.DeleteModel(
            name='MediaPartnerConference',
        ),
        migrations.DeleteModel(
            name='Presence',
        ),
    ]
