# Generated by Django 2.2.10 on 2020-02-25 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0019_add_stripe_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assopy.Order'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='talk',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
