# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-04 06:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0020_make_gender_field_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conference.Conference'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assopy.Order'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='talk',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
