# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-04 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0021_alter_add_deletion_PROTECT'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorincome',
            name='tags',
            field=models.CharField(blank=True, help_text='comma separated list of tags. Something like: special, break, keynote', max_length=200),
        ),
    ]
