# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-20 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0022_alter_sponsorincome_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='conference',
            field=models.CharField(help_text='Name of the conference', max_length=20),
        ),
        migrations.AlterField(
            model_name='track',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.TextField(help_text='HTML supported', verbose_name='Track title'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.CharField(max_length=20, verbose_name='Track name'),
        ),
    ]
