# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-27 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0023_update_field_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('canceled', 'Canceled'), ('waitlist', 'Waitlist'), ('declined', 'Declined')], default='proposed', max_length=8),
        ),
    ]
