# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-17 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0024_add_talk_status_declined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='type',
            field=models.CharField(choices=[('t_30', 'Talk (30 mins)'), ('t_45', 'Talk (45 mins)'), ('t_60', 'Talk (60 mins)'), ('i_60', 'Interactive (60 mins)'), ('r_180', 'Training (180 mins)'), ('p_45', 'Poster session (45 mins)'), ('p_180', 'Poster session (180 mins)'), ('n_60', 'Panel (60 mins)'), ('n_90', 'Panel (90 mins)'), ('h_180', 'Help desk (180 mins)')], default='t_30', max_length=5),
        ),
    ]
