# Generated by Django 2.2.19 on 2021-05-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0029_talk_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchaquestion',
            name='answer',
            field=models.CharField(max_length=255, verbose_name='answer (use a regular expression\n                                to capture possible answers e.g.\n                                "(python|the python programming language)"\n                                case is ignored)\n                                '),
        ),
    ]
