# Generated by Django 2.2.19 on 2021-05-22 13:40

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0029_talk_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True, help_text='Is this set visible to enduser?')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('streams', django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='Stream definitions as JSON list')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conference.Conference')),
            ],
        ),
    ]
