# Generated by Django 2.2.19 on 2021-05-24 14:07

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0030_add_streamset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamset',
            name='streams',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='Stream definitions as JSON list, with one entry per track in\nthe stream set. Order is important. The stream page will default to showing the first\ntrack. Example:\n[\n    {\n        "title": "Holy Grail",\n        "fare_codes": ["TRCC", "TRCP", "TRSC", "TRSP", "TRVC", "TRVP"],\n        "url": "https://www.youtube.com/embed/EEIk7gwjgIM"\n    }\n]\n'),
        ),
    ]
