# Generated by Django 2.2.24 on 2021-07-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0031_update_streamset_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchaquestion',
            name='answer',
            field=models.CharField(max_length=255, verbose_name='answer (use a regular expression to capture possible answers e.g. "(python|the python programming language)" case is ignored)'),
        ),
    ]
