# Generated by Django 2.2.17 on 2020-12-03 18:26

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketConference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_size', models.CharField(choices=[(None, 'Please select your shirt size!'), ('fs', 'S (fitted cut)'), ('fm', 'M (fitted cut)'), ('fl', 'L (fitted cut)'), ('fxl', 'XL (fitted cut)'), ('fxxl', 'XXL (fitted cut)'), ('fxxxl', '3XL (fitted cut)'), ('s', 'S (straight cut)'), ('m', 'M (straight cut)'), ('l', 'L (straight cut)'), ('xl', 'XL (straight cut)'), ('xxl', 'XXL (straight cut)'), ('xxxl', '3XL (straight cut)'), ('xxxxl', '4XL (straight cut)')], default=None, max_length=5, null=True)),
                ('python_experience', models.PositiveIntegerField(choices=[(0, 'no comment'), (1, '1 star  (just starting)'), (2, '2 stars (beginner)'), (3, '3 stars (intermediate)'), (4, '4 stars (expert))'), (5, '5 stars (guru level)')], default=0, null=True)),
                ('diet', models.CharField(choices=[(None, 'Please select your dietary preferences!'), ('omnivorous', 'Omnivorous'), ('vegetarian', 'Vegetarian'), ('other', 'Other')], default=None, max_length=10, null=True)),
                ('tagline', models.CharField(blank=True, help_text='a (funny?) tagline that will be displayed on the badge<br />Eg. CEO of FooBar Inc.; Super Python fanboy; Simple is better than complex.', max_length=60)),
                ('days', models.TextField(blank=True, verbose_name='Days of attendance')),
                ('badge_image', models.ImageField(blank=True, help_text="A custom badge image instead of the python logo.Don't use a very large image, 250x250 should be fine.", null=True, upload_to='p3/tickets/badge_image')),
                ('assigned_to', models.EmailField(blank=True, help_text='Email of the attendee for whom this ticket was bought.', max_length=254)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p3_conference', to='conference.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakerConference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_time', models.BooleanField(default=False)),
                ('speaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p3_speaker', to='conference.Speaker')),
            ],
        ),
        migrations.CreateModel(
            name='P3Profile',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='p3_profile', serialize=False, to='conference.AttendeeProfile')),
                ('tagline', models.CharField(blank=True, help_text='describe yourself in one line!', max_length=60)),
                ('twitter', models.CharField(blank=True, max_length=80)),
                ('image_gravatar', models.BooleanField(default=False)),
                ('image_url', models.URLField(max_length=500)),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=2)),
                ('spam_recruiting', models.BooleanField(default=False)),
                ('spam_user_message', models.BooleanField(default=False)),
                ('spam_sms', models.BooleanField(default=False)),
                ('interests', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='conference.ConferenceTaggedItem', to='conference.ConferenceTag', verbose_name='Tags')),
            ],
        ),
    ]
