
# Generated by Django 1.9.13 on 2018-10-09 18:46


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sprintpresence',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='sprintpresence',
            name='user',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Sprint',
        ),
        migrations.DeleteModel(
            name='SprintPresence',
        ),
    ]
