# Generated by Django 1.11.20 on 2019-05-05 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('p3', '0002_remove_unused_models')]

    operations = [
        migrations.AddField(
            model_name='ticketconference',
            name='name',
            field=models.CharField(
                default='',
                help_text='What name should appear on the badge?',
                max_length=255,
            ),
            preserve_default=False,
        )
    ]
