# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-16 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0004_mystery_migrations_maybe_2_to_3_bytes_to_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketconference',
            name='diet',
            field=models.CharField(choices=[(None, 'Please select your dietary preferences!'), ('omnivorous', 'Omnivorous'), ('vegetarian', 'Vegetarian'), ('other', 'Other')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticketconference',
            name='shirt_size',
            field=models.CharField(choices=[(None, 'Please select your shirt size!'), ('fs', 'S (female)'), ('fm', 'M (female)'), ('fl', 'L (female)'), ('fxl', 'XL (female)'), ('fxxl', 'XXL (female)'), ('fxxxl', '3XL (female)'), ('s', 'S (male)'), ('m', 'M (male)'), ('l', 'L (male)'), ('xl', 'XL (male)'), ('xxl', 'XXL (male)'), ('xxxl', '3XL (male)'), ('xxxxl', '4XL (male)')], default=None, max_length=5, null=True),
        ),
    ]
