# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-11 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0005_auto_shirt_and_dietary_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p3talk',
            name='talk',
        ),
        migrations.DeleteModel(
            name='P3Talk',
        ),
    ]
