# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-17 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p3', '0007_auto_20200217_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketconference',
            name='name',
        ),
    ]
